USE UOF

SELECT * FROM dbo.TB_WKF_TASK
ORDER BY BEGIN_TIME DESC

SELECT CURRENT_DOC FROM dbo.TB_WKF_TASK
ORDER BY BEGIN_TIME DESC

SELECT *FROM dbo.LYV_BusinessTripReport
SELECT * FROM dbo.LYV_BusinessTrip
SELECT * FROM dbo.LYV_BusinessTripOD


