USE TB_ERP

SELECT ST_NHANVIEN.NV_Ma, 
       ST_NHANVIEN.NV_Ten, 
       ST_NHANVIEN.DV_MA_, 
       ISNULL(ST_NHANVIENTHOIVIEC.NV_Ma, 'Employee') AS Flag, 
       ST_DONVI.KHU 
FROM ST_NHANVIEN 
LEFT JOIN ST_NHANVIENTHOIVIEC ON ST_NHANVIENTHOIVIEC.NV_Ma = ST_NHANVIEN.NV_Ma 
LEFT JOIN ST_DONVI ON ST_DONVI.DV_MA = ST_NHANVIEN.DV_MA 
WHERE ST_NHANVIEN.NV_Ma =  '" + UserID + "'
